import Foundation
import PackagePlugin

/// Generates `BuildInfo` from git so `--version` reports the tag and commit the
/// binary was built from, instead of a constant that drifts.
///
/// The git refs are declared as build inputs: without them the build system
/// caches the generated file and keeps reporting the commit it first saw.
/// Outside a git checkout (a source tarball, for instance) the stamp falls back
/// to `fallbackVersion` and reports no commit.
@main
struct VersionStamp: BuildToolPlugin {
    /// Used when git is unavailable; keep in step with the latest tag.
    static let fallbackVersion = "0.0.0"

    func createBuildCommands(context: PluginContext, target: Target) throws -> [Command] {
        let packageDirectory = context.package.directoryURL
        let outputFile = context.pluginWorkDirectoryURL.appending(path: "BuildInfo.swift")

        let script = """
            set -e
            cd "\(packageDirectory.path())"

            tag=$(git describe --tags --abbrev=0 2>/dev/null || true)
            commit=$(git rev-parse --short HEAD 2>/dev/null || true)

            if [ -n "$tag" ]; then
                version=${tag#v}
                ahead=$(git rev-list --count "$tag"..HEAD 2>/dev/null || echo 0)
                if [ "$ahead" != "0" ]; then
                    version="$version+$ahead"
                fi
            else
                version="\(Self.fallbackVersion)"
            fi

            cat > "\(outputFile.path())" <<SWIFT
            // Generated by the VersionStamp plugin. Do not edit.
            enum BuildInfo {
                static let version = "$version"
                static let commit = "$commit"
            }
            SWIFT
            """

        return [
            .buildCommand(
                displayName: "Stamping version from git",
                executable: URL(fileURLWithPath: "/bin/sh"),
                arguments: ["-c", script],
                inputFiles: gitInputs(in: packageDirectory),
                outputFiles: [outputFile]
            )
        ]
    }

    /// The git files whose contents decide the stamp: the checked-out branch, the
    /// commit it points at, and the tags. Missing entries are simply not declared.
    private func gitInputs(in packageDirectory: URL) -> [URL] {
        let gitDirectory = packageDirectory.appending(path: ".git")
        let head = gitDirectory.appending(path: "HEAD")

        var candidates = [
            head,
            gitDirectory.appending(path: "packed-refs"),
            gitDirectory.appending(path: "refs/tags")
        ]

        // `.git/HEAD` only changes when the branch does; the branch ref changes on
        // every commit, so follow it.
        if let contents = try? String(contentsOf: head, encoding: .utf8),
            contents.hasPrefix("ref: ") {
            let reference = contents
                .dropFirst("ref: ".count)
                .trimmingCharacters(in: .whitespacesAndNewlines)
            candidates.append(gitDirectory.appending(path: reference))
        }

        return candidates.filter { FileManager.default.fileExists(atPath: $0.path) }
    }
}
