import Foundation
import PackagePlugin

/// Generates `BuildInfo` before every build so `--version` reports the git tag
/// and commit the binary was built from, instead of a constant that drifts.
///
/// Outside a git checkout (a source tarball, for instance) it falls back to
/// `fallbackVersion` below.
@main
struct VersionStamp: BuildToolPlugin {
    /// Used when git is unavailable; keep in step with the latest tag.
    static let fallbackVersion = "0.3.0"

    func createBuildCommands(context: PluginContext, target: Target) throws -> [Command] {
        let outputDirectory = context.pluginWorkDirectoryURL
        let outputFile = outputDirectory.appending(path: "BuildInfo.swift")

        let script = """
            set -e
            cd "\(context.package.directoryURL.path())"

            tag=$(git describe --tags --abbrev=0 2>/dev/null || true)
            commit=$(git rev-parse --short HEAD 2>/dev/null || true)

            if [ -n "$tag" ]; then
                version=${tag#v}
                ahead=$(git rev-list --count "$tag"..HEAD 2>/dev/null || echo 0)
                if [ "$ahead" != "0" ]; then
                    version="$version+$ahead"
                fi
            else
                version="\(Self.fallbackVersion)"
            fi

            cat > "\(outputFile.path())" <<SWIFT
            // Generated by the VersionStamp plugin. Do not edit.
            enum BuildInfo {
                static let version = "$version"
                static let commit = "$commit"
            }
            SWIFT
            """

        return [
            .prebuildCommand(
                displayName: "Stamping version from git",
                executable: URL(fileURLWithPath: "/bin/sh"),
                arguments: ["-c", script],
                outputFilesDirectory: outputDirectory
            )
        ]
    }
}
